// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FocusArea } from "./FocusArea";

export type About = { 
/**
 * Paragraphs for the "Background" subsection.
 */
background: Array<string>, focus_areas: Array<FocusArea>, };
