// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSource } from "./ProjectSource";
import type { SiteFile } from "./SiteFile";

/**
 * Everything admin edits, from `GET /api/admin/content` and returned by every save.
 */
export type AdminContent = { 
/**
 * Send back as `If-Match` when saving; a save based on older content is refused (409).
 */
version: string, site: SiteFile, projects: Array<ProjectSource>, has_resume: boolean, };
