// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ContactRequest = { name: string, email: string, message: string, 
/**
 * Honeypot: a visually hidden field that people leave empty and bots fill in.
 */
website?: string, 
/**
 * How long the form was open before it was submitted, in milliseconds.
 */
elapsed_ms: number, };
