// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Education = { school: string, degree: string, location: string, start: string, end: string | null, details: Array<string>, };
