// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldError } from "./FieldError";

/**
 * JSON body of every API error response.
 */
export type ErrorBody = { error: string, 
/**
 * Per-field problems; only non-empty for validation errors.
 */
fields: Array<FieldError>, };
