// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Experience = { company: string, company_url: string | null, title: string, location: string, 
/**
 * Display dates, e.g. "Jun 2023".
 */
start: string, 
/**
 * `None` means current; the first such entry becomes the home page's "Current Role".
 */
end: string | null, 
/**
 * One-line summary for the "Current Role" section.
 */
summary: string | null, bullets: Array<string>, };
