// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

/**
 * TOML front matter at the top of `content/projects/<slug>.md`.
 */
export type FrontMatter = { title: string, 
/**
 * Short label above the title, e.g. "Full-stack" or "Game · Bevy".
 */
category: string, summary: string, tags: Array<string>, featured: boolean, 
/**
 * Sort key for project lists, ascending; ties sort by title.
 */
order: number, date: string | null, image: string | null, links: Array<Link>, };
