// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PhotoDetails } from "./PhotoDetails";

/**
 * A `[[galleries]]` entry in site.toml. Its photos aren't listed here: they're whatever images
 * are in `photos/<folder>/` in the media bucket, listed when /api/photos is requested.
 */
export type GalleryConfig = { 
/**
 * Folder under `photos/`, e.g. "stealth-startup".
 */
folder: string, title: string, description: string | null, 
/**
 * Optional details per photo, keyed by file name ("01.jpg").
 */
photos: { [key in string]: PhotoDetails }, };
