// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Photo } from "./Photo";

/**
 * A gallery as served by /api/photos: its settings plus the photos found in its folder.
 */
export type Gallery = { 
/**
 * Its folder under `photos/`; admin finds the gallery by it.
 */
folder: string, title: string, description: string | null, photos: Array<Photo>, };
