// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Gallery } from "./Gallery";

export type PhotosResponse = { 
/**
 * Galleries from site.toml, each with the photos currently in its media folder.
 */
galleries: Array<Gallery>, };
