// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type PhotoDetails = { alt: string | null, caption: string | null, date: string | null, };
