// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Photo = { 
/**
 * Image URL, e.g. "/photos/stealth-startup/01.jpg" (served from the media bucket).
 */
src: string, 
/**
 * Describes the photo for screen readers.
 */
alt: string, caption: string | null, 
/**
 * Label on the Time Machine scrubber, e.g. "Jun 2026".
 */
date: string | null, };
