// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Profile = { name: string, 
/**
 * Role line under the name, e.g. "Software Engineer".
 */
headline: string, location: string, 
/**
 * One or two sentences for the hero.
 */
tagline: string, email: string, 
/**
 * Image path served by the frontend, e.g. "/headshot.jpg" for `frontend/public/headshot.jpg`.
 */
headshot: string | null, };
