// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Link } from "./Link";

export type ProjectSummary = { 
/**
 * The project's file name without `.md`.
 */
slug: string, title: string, category: string, summary: string, tags: Array<string>, featured: boolean, date: string | null, image: string | null, links: Array<Link>, };
