// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontMatter } from "./FrontMatter";

/**
 * A project as admin saves it.
 */
export type ProjectInput = { front: FrontMatter, markdown: string, };
