// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FrontMatter } from "./FrontMatter";

/**
 * A project file as admin edits it: the front matter and the Markdown below it.
 */
export type ProjectSource = { 
/**
 * The file name without `.md`.
 */
slug: string, front: FrontMatter, markdown: string, };
