// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectSummary } from "./ProjectSummary";
import type { Tag } from "./Tag";

export type ProjectsResponse = { projects: Array<ProjectSummary>, 
/**
 * All tags, regardless of the `tag` filter, so the filter UI can list them.
 */
tags: Array<Tag>, };
