// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Award } from "./Award";
import type { Education } from "./Education";
import type { Experience } from "./Experience";
import type { Profile } from "./Profile";
import type { SkillGroup } from "./SkillGroup";
import type { Social } from "./Social";

export type ResumeResponse = { profile: Profile, socials: Array<Social>, experience: Array<Experience>, education: Array<Education>, skill_groups: Array<SkillGroup>, awards: Array<Award>, 
/**
 * Whether `/api/resume.pdf` is available.
 */
has_pdf: boolean, };
