// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { About } from "./About";
import type { Experience } from "./Experience";
import type { Profile } from "./Profile";
import type { Social } from "./Social";
import type { Tag } from "./Tag";

/**
 * Everything the home page, nav, and footer need.
 */
export type SiteResponse = { profile: Profile, about: About, socials: Array<Social>, current_role: Experience | null, 
/**
 * Project tags, most-used first.
 */
skills: Array<Tag>, };
