// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { About } from "./About";
import type { Award } from "./Award";
import type { Education } from "./Education";
import type { Experience } from "./Experience";
import type { GalleryConfig } from "./GalleryConfig";
import type { Profile } from "./Profile";
import type { SkillGroup } from "./SkillGroup";
import type { Social } from "./Social";

/**
 * `content/site.toml`, which admin edits as a whole.
 */
export type SiteFile = { profile: Profile, about: About, socials: Array<Social>, experience: Array<Experience>, education: Array<Education>, skill_groups: Array<SkillGroup>, awards: Array<Award>, galleries: Array<GalleryConfig>, };
