// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A resume "Technical Skills" row, e.g. "Languages: Rust, TypeScript".
 */
export type SkillGroup = { name: string, skills: Array<string>, };
