// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SocialKind } from "./SocialKind";

export type Social = { kind: SocialKind, label: string, url: string, };
