// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRef } from "./ProjectRef";

/**
 * A project tag and the projects that use it (the home page's "Skills" list).
 */
export type Tag = { name: string, projects: Array<ProjectRef>, };
