// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where and how to upload a file, from `POST /api/admin/uploads`.
 */
export type UploadTicket = { 
/**
 * PUT the file's bytes here.
 */
url: string, 
/**
 * Headers to send with that PUT, as name/value pairs.
 */
headers: Array<[string, string]>, 
/**
 * Where the file is served once uploaded, e.g. "/photos/trip/01.jpg".
 */
path: string, };
