// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UploadKind } from "./UploadKind";

export type UploadRequest = { kind: UploadKind, 
/**
 * The gallery folder, for photos.
 */
folder: string | null, 
/**
 * The file's name on your computer: its extension picks the type, and photos keep a
 * cleaned-up version of the name (they're shown in name order).
 */
filename: string, };
